# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

#Project Properties
javaVersion=25
javaToolchainVersion=25

# Fabric Properties
minecraftVersion=26.2
loaderVersion=0.19.3
fabricKotlinVersion=1.13.12+kotlin.2.4.0

# Mod Properties
modVersion=1.1.0
mavenGroup=com.github.exopandora
archivesBaseName=worldupgrader
