[versions]
minecraft = "26.3"
kotlin = "2.4.20"
fabric-loader = "0.19.5"
fabric-kotlin = "1.14.1+kotlin.2.4.20"

[libraries]
minecraft-fabric = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }

[plugins]
fabricloom = { id = "net.fabricmc.fabric-loom", version = "1.17-SNAPSHOT" }
kotlin = { id = 'org.jetbrains.kotlin.jvm', version.ref = "kotlin" }
